# Generated by Django 2.0.7 on 2018-08-22 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('bill_name', models.CharField(max_length=250)),
                ('bill_content', models.TextField()),
                ('date_first_posted', models.DateField(default=datetime.datetime(2018, 8, 22, 14, 53, 37, 358524, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('house_code', models.CharField(max_length=2)),
            ],
        ),
    ]
